# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LTKit' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for LTKit

pod 'AFNetworking', '~> 3.1.0'	# 网络框架

pod 'SDWebImage', '~> 3.7.2'	# 网络图片加载框架

pod 'Masonry', '~> 1.0.2'	# 页面适配框架

pod 'YYKit', '~> 1.0.9'		# YYKit

pod 'MJExtension', '~> 3.0.13'	# 数据解析 json -> model

pod 'MJRefresh', '~> 3.1.12'	# 下拉刷新,上拉加载

pod 'MBProgressHUD', '~> 0.9'	# 加载菊花

pod 'IQKeyboardManager', '~> 4.0.10'	# 键盘管理工具

pod 'ReactiveObjC', '~> 3.0.0'	# RAC

  target 'LTKitTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LTKitUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
